# Site settings
title: Panda Team
email: contato@pandateam.com.br
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.pandateam.com.br" # the base hostname & protocol for your site

twitter_username:
github_username: panda-team

# Build settings
markdown: kramdown
