# Site settings
title: Panda Team
email: contato@pandateam.com.br
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.pandateam.com.br" # the base hostname & protocol for your site
#permalink: /blog/:year/:month/:day/:title/
twitter_username: PandateamBr
github_username: panda-team
paginate: 8
paginate_path: "/blog/page:num/"
# Build settings
markdown: kramdown
gems: [jekyll-paginate]
